// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwvcgawjkltegcnyyryo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3dmNnYXdqa2x0ZWdjbnl5cnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTkwNTAsImV4cCI6MjA3MjY5NTA1MH0.eubl5fz8FMa3U1Vi1nl6sYppq9tw52ClhxngqLEaH4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});